[build]
  command = "npm install --ignore-scripts && npm --workspace @cl-monad/terminal run build"
  publish = "packages/terminal/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
